In [1]:
import numpy as np
from scipy.io import loadmat

import matplotlib.pyplot as plt
%matplotlib inline 

from sklearn.neighbors import KNeighborsClassifier

# confusion matrix
from sklearn import metrics
# http://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html




#from tqdm import tqdm # for progressive bar

from sklearn.externals import joblib # to save model


from P300.data import load_data


## k-nearest neighbor classifier

In [2]:
subject_train = 'A'
subject_test = 'A'
X_train, Y_train, Code_train = load_data(subject_train, 'train', 85)
X_test, Y_test, Code_test = load_data(subject_test, 'test', 100)

loaded:
(85, 180, 896)
(85, 180, 1)
(85, 180, 1)
stacked:
(15300, 896)
(15300,)
(15300,)
loaded:
(100, 180, 896)
(100, 180, 1)
(100, 180, 1)
stacked:
(18000, 896)
(18000,)
(18000,)


In [3]:
clf = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)
clf.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
           weights='uniform')

In [4]:
num_ch = 64
joblib.dump(clf, "{}_kNN_ch{}.model".format(subject_train, num_ch))

['A_kNN_ch64.model']

In [5]:
# predict
Y_est=clf.predict(X_test)

#accuracy = 
sum(Y_test==Y_est) / len(Y_test)

0.8052777777777778

In [6]:
# confusion matrix
from sklearn import metrics
# http://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html

metrics.confusion_matrix(Y_test,Y_est,labels=(1,-1))

array([[  175,  2825],
       [  680, 14320]])

## subject B

In [7]:
subject_train = 'B'
subject_test = 'B'
X_train, Y_train, Code_train = load_data(subject_train, 'train', 85)
X_test, Y_test, Code_test = load_data(subject_test, 'test', 100)

loaded:
(85, 180, 896)
(85, 180, 1)
(85, 180, 1)
stacked:
(15300, 896)
(15300,)
(15300,)
loaded:
(100, 180, 896)
(100, 180, 1)
(100, 180, 1)
stacked:
(18000, 896)
(18000,)
(18000,)


In [8]:
# train
clf = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)
clf.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
           weights='uniform')

In [9]:
# save model
num_ch = 64
joblib.dump(clf, "{}_kNN_ch{}.model".format(subject_train,num_ch))

['B_kNN_ch64.model']

In [10]:
# test
Y_est=clf.predict(X_test)

#accuracy = 
sum(Y_test==Y_est) / len(Y_test)

0.8153333333333334

In [11]:
# confusion matrix
metrics.confusion_matrix(Y_test,Y_est,labels=(1,-1))

array([[  154,  2846],
       [  478, 14522]])

## Joint

In [12]:
subject_train = 'A'
subject_test = 'A'
X_train_A, Y_train_A, Code_train_A = load_data(subject_train, 'train', 85)
X_test_A, Y_test_A, Code_test_A = load_data(subject_test, 'test', 100)

subject_train = 'B'
subject_test = 'B'
X_train_B, Y_train_B, Code_train_B = load_data(subject_train, 'train', 85)
X_test_B, Y_test_B, Code_test_B = load_data(subject_test, 'test', 100)


loaded:
(85, 180, 896)
(85, 180, 1)
(85, 180, 1)
stacked:
(15300, 896)
(15300,)
(15300,)
loaded:
(100, 180, 896)
(100, 180, 1)
(100, 180, 1)
stacked:
(18000, 896)
(18000,)
(18000,)
loaded:
(85, 180, 896)
(85, 180, 1)
(85, 180, 1)
stacked:
(15300, 896)
(15300,)
(15300,)
loaded:
(100, 180, 896)
(100, 180, 1)
(100, 180, 1)
stacked:
(18000, 896)
(18000,)
(18000,)


In [13]:
# combine
X_train = np.vstack((X_train_A,X_train_B))
print(X_train.shape)
Y_train = np.concatenate((Y_train_A, Y_train_B))
print(Y_train.shape)

X_test = np.vstack((X_test_A, X_test_B))
print(X_test.shape)
Y_test = np.concatenate((Y_test_A, Y_test_B))
print(Y_test.shape)




(30600, 896)
(30600,)
(36000, 896)
(36000,)


In [14]:
# train
clf = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)
clf.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
           weights='uniform')

In [15]:
# save model
subject_train = 'AandB'
num_ch = 64
joblib.dump(clf, "{}_kNN_ch{}.model".format(subject_train,num_ch)) 
    

['AandB_kNN_ch64.model']

In [16]:
# predict
Y_est=clf.predict(X_test)

#accuracy = 
sum(Y_test==Y_est) / len(Y_test)

0.8131944444444444

In [17]:
# confusion matrix
metrics.confusion_matrix(Y_test,Y_est,labels=(1,-1))

array([[  288,  5712],
       [ 1013, 28987]])

In [18]:
# predict A using joint model
Y_est_A=clf.predict(X_test_A)

#accuracy = 
sum(Y_test_A==Y_est_A) / len(Y_test_A)



0.8117222222222222

In [19]:
# predict B using joint model

Y_est_B=clf.predict(X_test_B)

#accuracy = 
sum(Y_test_B==Y_est_B) / len(Y_test_B)



0.8146666666666667